#!/bin/bash

alias gcob="git checkout -b"
alias gco="git checkout"
alias gs="git status"
alias gh="git hist"
alias gb="git branch"

gfump() {
	name="$1"
	if [ -z "$1" ]; then 
		name="master"
	fi
	git fetch upstream
	git merge upstream/$name
	git push -u origin $name
}

gac() {
	git add "$@"
	git commit
}

gm() {
	name="$1"
	if [ -z "$1" ]; then 
		name="master"
	fi
	git merge $name
}

gacp() {
	git add "$@"
	git commit
	git push
}

grau() {
	git remote add upstream http://github.com/${1}.git
}

gcl() {
	git clone http://github.com/${1}.git $2
}

