#!/bin/bash

alias gcob="git checkout -b"
alias gco="git checkout"
alias gs="git status"
alias gh="git hist"
alias gb="git branch"
alias grc="git rebase --continue"
alias gri="git rebase -i"
alias gci="git commit"
alias gh="git hist | head -n 10"
alias gpu="git push -u origin"
alias gpf="git push -f origin"
alias gd="git diff"
alias gg="git grep"

grih() {
  git rebase -i HEAD~$1
}

gfump() {
	name="$1"
	if [ -z "$1" ]; then 
		name="master"
	fi
	git fetch upstream
	git merge upstream/$name
	git push -u origin $name
}

gac() {
	git add "$@"
	git commit
}

gm() {
	name="$1"
	if [ -z "$1" ]; then 
		name="master"
	fi
	git merge $name
}

gacp() {
	git add "$@"
	git commit
	git push
}

grau() {
	git remote add upstream http://github.com/${1}.git
}

gcl() {
	git clone http://github.com/${1}.git $2
}

