#!/bin/bash

ln -sf /Users/larioj/Config/bash/bash_common ~/.bash_common
ln -sf /Users/larioj/Config/git/gitconfig ~/.gitconfig
ln -sf /Users/larioj/Config/git/gitrc ~/.gitrc
ln -sf /Users/larioj/Config/mac/bash/bash_aliases ~/.bash_aliases
ln -sf /Users/larioj/Config/mac/bash/bashrc ~/.bashrc
ln -sf /Users/larioj/Config/mac/bash/profile ~/.profile
ln -sf /Users/larioj/Config/vim/vimrc ~/.vimrc
