call plug#begin()
"Plug 'scrooloose/syntastic'
Plug 'tpope/vim-sensible'
Plug 'ervandew/supertab'
Plug 'vim-airline/vim-airline'
Plug 'derekwyatt/vim-scala'
Plug 'vim-scripts/vim-auto-save'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'godlygeek/tabular'
call plug#end()

syntax on
set nocompatible
filetype plugin indent on
let g:airline#extensions#tabline#enabled = 1
"set spell
set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab

"set smartindent
"set tabstop=4
"set shiftwidth=4
set number

"syntax enable

inoremap {<CR> {<CR>}<Esc>ko

"Leader
let mapleader=" "

"Tab navigation
nnoremap <leader>n :tabnext<CR>
nnoremap <leader>p :tabprev<CR>
nnoremap <leader>m :tabm<Space>

" Bash Aliases in Vim
let $BASH_ENV = "~/.bash_aliases"

nnoremap ; :
nnoremap : ;
nnoremap h j
vnoremap h j
nnoremap t k
vnoremap t k
nnoremap j t
vnoremap j t
"nnoremap v <C-v>
"vnoremap v <C-v>
"nnoremap <C-v> v
"vnoremap <C-v> v


nnoremap - <C-z>
nnoremap <leader>- ZZ

set mouse=a

"Ctags Shortcuts
nnoremap <leader>i <C-]>
nnoremap <leader>o <C-T>

"set pastetoggle=<leader>p

let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
let g:auto_save_silent = 1
let g:auto_save_events = ["InsertLeave"]


"nnoremap j :m .+1<CR>==
"nnoremap k :m .-2<CR>==
