#!/bin/bash

alias s="history | grep"
alias ls="ls -Gh"
alias e="exit"
alias c="clear"
alias f="find . -name"

jfmti() {
  python -m json.tool $1 > aoeuaeuaoueao && \
    mv aoeuaeuaoueao $1
}

jfmta() {
  for F in $(find . -name '*json'); do
    jfmti $F
  done
}
