#!/bin/bash

# Nice little prompt
PS1="$ "

alias s="history | grep"

# Set vim mode
set -o vi

# Find name
alias findn="find . -name"

# I always forget how to tar
alias untar="tar -vxzf"
alias maketar="tar -cvzf"

# Memory usage
alias mem="du -hsc"

# make executable
mx () {
	touch $@
	chmod u+x $@
}

# Make and move to directory
alias md="mkdir"
mm () {
	mkdir $1 && cd $1
}
alias mf="touch"

# Editor
e() {
	bide c $1
	nvim $1
}
alias ec="vim"
alias ecd="/opt/eclipse/eclimd &>/dev/null &"

fp() {
	grep -rnw "$1" -e "$2"
}
