#!/bin/bash

# Nice little prompt
PS1="\W\$ "

# Search history
alias s="history | grep"

# Find name
alias findfile="find . -name"

# I always forget how to tar
alias untar="tar -vxzf"
alias maketar="tar -cvzf"

# Memory usage
alias showmem="du -hsc"

# Make executable
touchx () {
	touch $@
	chmod u+x $@
}

# Make and move to directory
alias md="mkdir"
mkcd () {
	mkdir $1 && cd $1
}

findtext() {
	grep -rnw "$1" -e "$2"
}

# Convenience
alias c='clear'
alias q='exit'
